In [ ]:
a=int(input("Enter the number"))
b=int(input("Enter the number"))
if a>b:
    print("a is greater than b")
if b>a:
    print("b is greater than a")
    



In [ ]:
a=int(input("Enter the number"))
b=int(input("Enter the number"))
if a>b:
    print("a is greater than b")
else:
    print("b is greater than a")

b is greater than a


In [ ]:
a=int(input("Enter the number"))
b=int(input("Enter the number"))
if a>0:
    print("a is positive")
else:
    print("a is negative")



a is negative


In [ ]:
a=int(input("Enter the number"))
b=int(input("Enter the number"))
if a==b:
    print("Entered number are equal")
else:
    print("Entered number are not equal")


Entered number are not equal


In [ ]:
a=int(input("Enter the number"))

if a%2==0:
    print("Entered number is even")
else:
    print("Entered number is odd")

Entered number is even


In [ ]:
a=int(input("Enter the number"))

if a%3==0:
    print("a is divisble by 3")
if a%5==0:
    print("a is divisble by 5")

a is divisble by 5


In [ ]:
a=int(input("Enter first no"))
b=int(input("Enter the second no"))

if a>b:
    print("a is greater")
elif a==b:
    print("both are same")
else:
    print("b is greater")
      

b is greater


In [ ]:
a=int(input("Enter the no 1"))
b=int(input("Enter the no 2"))
c=int(input("Enter the no 3"))

if a>b and a>c:
    print("a is greater")
elif b>c and b>a:
    print("b is greater")
else:
    print ("c is greater")



c is greater


In [ ]:
Balance=1000
m=int(input("Enter total money:"))

if m>=20 and m<40:
   print("per kg price ",m," and total qty ",8," now total bill is ",m*8," and after purches the remaining amount is ",Balance-m*8)
elif m>=40 and m<60:
   print("per kg price ",m," and total qty ",6," now total bill is ",m*6," and after purches the remaining amount is ",Balance-m*6)
elif m>=60 and m<=80:
   print("per kg price ",m," and total qty ",4," now total bill is ",m*4," and after purches the remaining amount is ",Balance-m*4)
else:
    print("price is to high or quality issue")

per kg price  50  and total qty  6  now total bill is  300  and after purches the remaining amount is  700


In [ ]:
Balance=1000
m=int(input("Enter per unit consumption"))
if m<50:
    print("per unit consumotion",m,"total unit consumption",5,"total bill is",m*5)
elif m>=50 and m<120:
   print("per unit consumotion",m,"total unit consumption",7,"total bill is",m*7)
elif m>=120 and m<180:
   print("per unit consumotion",m,"total units consumption",9,"total bill is",m*9)
elif m>=180 and m<=250:
   print("per unit consumotion",m,"total unit consumption",11,"total bill is",m*11)
elif m>250:
   print("per unit consumotion",m,"total unit consumption",50,"total bill is",m*50)
else:
   print ("unit consumption cannot be identified")

per unit consumotion 150 total units consumption 9 total bill is 1350


In [ ]:
Balance=20000
print("profile or deposit or withdrawl")
m=(input("Enter profile"))
if m=='profile':
    print("name-Jashnavi singidi, account number=18009689 is",Balance,)
 
elif m=='deposit':
    x=int(input("Enter deposit or withdrawl"))
    print("deposit is",x,"total deposit is",Balance+x)
elif m=='withdrawl':
    amt=int(input())
    print("withdrawl is",amt,"Total withdrawl is",Balance-amt)
else:
    print("Invalid syntax")

profile or deposit or withdrawl
withdrawl is 400 Total withdrawl is 19600


In [ ]:
a=int(input("Enter the  number"))
b=int(input("Enter the number"))
m=(input("add,sub,"))
if m=='add':
    print("add of variable is",a+b)
elif m=='sub':
    print("sub of variable is",a-b)

else:
    print("Invalid syntax")


sub of variable is -1


In [ ]:
a=int(input())
b=int(input())
c=int(input())

if a>b:
    if a>c:
        print("a is largest")
    else:
        print("c is largest")
else:
    if b>c:
        print("bis largest")
    else:
        print(" c is largest")

 c is largest


In [ ]:
a=int(input())
b=int(input())
c=int(input())

if a>b:
    if a>c:
        print("a is largest")
    else:
        print("c is largest")
else:
    if b>c:
        print("b is largest")
    else:
        print("c is largest")

c is largest


In [ ]:
a=int(input())

if a>0:
    if a%2==0:
        print("number is +ve even")
    else:
        print("number is +ve odd")
else:
    if a%2==0:
        print("number is -ve even")
    else:
        print("number is -ve odd")




number is -ve odd


In [ ]:
a=int(input("Enter the number"))
if a>0:
    if a%2==0

In [ ]:
if a>b:
    if c>b:
        if b:
            pass
        else:
            pass
    else:
        pass
else:
    pass


In [ ]:
#LOOP
a=int(input("Enter the number"))
i=1
while i<=a:
    if i%2==0:
        print(i,end=' ')
    i=i+1


2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 

In [ ]:
a=int(input("Enter the number"))
i=1
while i<=100:
    if i<=a:
        print(i)
    i=i+1


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
# loop
i=1
while i<=10:
    print(i,end=" ")
    i=i+1

1 2 3 4 5 6 7 8 9 10 

In [ ]:
a=int(input("Enter the number"))
i=1
while i<=10:
    print(i*a)
    i=i+1


5
10
15
20
25
30
35
40
45
50


In [ ]:
a=int(input("Enter the number"))

i=1
while i<=10:
    print(a,"X",i,"=",a*i)
    i=i+1

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20


In [ ]:
a=int(input("Enter the number"))
f=1
i=a
while i>=1:
    if i==1:
        print(i,"=",end=' ')
    else:
        print(i,"x",end=" ")
    f=f*i
    i=i-1
print(f)


5 x 4 x 3 x 2 x 1 = 120


In [ ]:
a=int(input("Enter the number"))
c=0
s=0
i=1
while i<=a:
    if i%2==0:
        c=c+1
        s=s+i
    i=i+1
print("sum ",s)
print("count ",c)
    
    
    


sum  650
count  25


In [ ]:
a=int(input("Enter the number"))
while i>=1:
    if i==1:
        print(i,"=",end=" ")
    else:
        print(i,"X",end=" ")


In [ ]:
a=int(input("Enter the number"))
i=2
while i<a:
    if a%i==0:
        print(i)
    i=i+1
    

2
4


In [ ]:
a=int(input("Enter the number"))
i=1
while i<=a:
    print(i)
    i=i+1



1
2
3
4


In [ ]:
a=int(input("Enter the number"))
i=1
while i<=a:
    print(i)
    i=i+3

1
4


In [ ]:
a=int(input("Enter the number"))
i=a
while i>=1:
    print(i)
    i=i-3

8
5
2


In [ ]:
a=int(input("Enter the number"))
i=a
while i>=1:
    print(i)
    i=i-1

10
9
8
7
6
5
4
3
2
1


In [ ]:
a=int(input("Enter the number"))
i=10
while i>=1:
    print(i*a)
    i=i-1

30
27
24
21
18
15
12
9
6
3


In [ ]:
y=int(input())
if y%100==0:
    if y%400==0:
        print("year is century and leap year")
    else:
        print("year is century but not leap year")
else:
    if y%4==0:
        print("year only leap year")
    else:
        print("year is not leap year")

year is century and leap year


In [1]:
i=1
while i<=10:
    print(i,end=" ")
    a=i
    j=1
    while j<=9:
        a=a+10
        print(a,end=" ")
        j=j+1
    print()
    i=i+1

1 11 21 31 41 51 61 71 81 91 
2 12 22 32 42 52 62 72 82 92 
3 13 23 33 43 53 63 73 83 93 
4 14 24 34 44 54 64 74 84 94 
5 15 25 35 45 55 65 75 85 95 
6 16 26 36 46 56 66 76 86 96 
7 17 27 37 47 57 67 77 87 97 
8 18 28 38 48 58 68 78 88 98 
9 19 29 39 49 59 69 79 89 99 
10 20 30 40 50 60 70 80 90 100 


In [ ]:
a=int(input("Enter the number"))
i=1
while i<=a:
    if a%i==0:
        print("factors",i)
    i=i+1

factors 1
factors 2
factors 4
factors 5
factors 8
factors 10
factors 20
factors 40


In [ ]:
a=int(input("Enter the number"))
c=0
i=2
while i<a:
    if a%i==0:
        c=1
    i=i+1
if c==0:
    print("prime number")
else:
    print("Not a prime number")

Not a prime number


In [ ]:
a=int(input("Enter the number"))
c=0
i=2
while i<a:
    if a%i==0:
        c=1
    i=i+1
if c==0:
    print("Prime number")
else:
    print("NON prime number")

In [ ]:
a=int(input("Enter the number"))
i=1
while i<=a:
    j=2
    c=0
    while j<i:
        if i%j==0:
            c=1
        j=j+1
    if c==0:
        print("prime number")

        

In [ ]:
a=int(input("Enter the number"))
i=a
while i>=1:
    if i%4==0:
        print(i)
    i=i-1

12
8
4


In [ ]:
a=int(input("enter the number"))
i=1
while i<=a:
    if i%4==0:
        print(i)
    i=i+1


4
8


In [ ]:
a=int(input("Enter the number:"))
i=2
while i<a:
    j=2
    c=0
    while j<i:
        if i%j==0:
            c=1
        j=j+1
    if c==0:
        print(i)
    i=i+18

2
3
5
7
11
13
17
19


In [ ]:
i=1
while i<=5:        # for row
    j=1
    while j<=5:      # for col of each row
        print("*",end=" ")
        j=j+1
    print()
    i=i+1

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
i=1
while i<=5:
    j=1
    while j<=i:        # col depend on row ex if row i=1 the j will be iterate 1 time if i=2 then j iterate 2 time
        print("*",end=" ")
        j=j+1
    print()
    i=i+1

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
i=1
while i<=5:
    j=5
    while j>=i:
        print("*",end=" ")
        j=j-1
    print()
    i=i+1

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
r=1
while r<=5:
    space=5
    while space>=r: #column depend on row
        print(' ',end=" ")
        space=space-1
    star=1
    while star<=r:
        print('*',end=" ")
        star=star+1
    print()
    r=r+1

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [ ]:
i=1
while i<=5:
    j=1
    while j<=i:
        print(' ',end=" ")
        j=j+1
    a=5
    while a>=i:
        print('*',end=" ")
        a=a-1
    print()
    i=i+1

  * * * * * 
    * * * * 
      * * * 
        * * 
          * 


In [ ]:
r=1
while r<=5:
    space=5
    while space>=r: #column depend on row
        print(' ',end=" ")
        space=space-1
    star=1
    while star<=r*2-1:
        print('*',end=" ")
        star=star+1
    print()
    r=r+1

          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [ ]:
i=1
while i<=5:
    print(' '*(5-i),'*'*(i*2-1))
    i=i+1

     *
    ***
   *****
  *******
 *********


In [ ]:
i=1
while i<=5:
    print(' '*(i),'*'*(11-i*2))
    i=i+1

  *********
   *******
    *****
     ***
      *


In [ ]:
i=1
while i<=5:
    print(' '*(5-i),'*'*(i*2-1))
    i=i+1
i=1
while i<=5:
    print(' '*(i-1),'*'*(11-i*2))
    i=i+1

     *
    ***
   *****
  *******
 *********
 *********
  *******
   *****
    ***
     *


In [ ]:
a=int(input("Eter the number"))
i=`12`
for i in range(1,a+1):
    if a%i==0:
        print("factors",i)
    i=i+1


factors 1
factors 7


In [ ]:
a=int(input("Enter the number"))
c=0
i=2
for i in range(2,a):
    if a%i==0:
        c=1
    i=i+1
if c==0:
    print("Prime number")
else:
    print("Non prime number")

Non prime number


In [ ]:
n=int(input("Enter the number"))
f=0
for i in range(2,n):

    if n%i==0:
        c=0
        for j in range(2,i):
            if i%j==0:
                c=1
        if c==0:
            print(i)
            f=1
if f==0:
    print("There is no prime factor")

2
3


In [ ]:

for i in range(1,11,1):
    print(i,end=" ")
    a=i
    for j in range(1,10,1):
        a=a+10
        print(a,end=" ")  
    print()

1 11 21 31 41 51 61 71 81 91 
2 12 22 32 42 52 62 72 82 92 
3 13 23 33 43 53 63 73 83 93 
4 14 24 34 44 54 64 74 84 94 
5 15 25 35 45 55 65 75 85 95 
6 16 26 36 46 56 66 76 86 96 
7 17 27 37 47 57 67 77 87 97 
8 18 28 38 48 58 68 78 88 98 
9 19 29 39 49 59 69 79 89 99 
10 20 30 40 50 60 70 80 90 100 


In [ ]:
for i in range(0,5):
    for j in range(0,5):
        print("*",end=" ")
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
for i in range(1,6):
    for j in range(1,i+1):
        print("*",end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [11]:
for i in range(1,6):
    for j in range(5,i-1,-1):
        print("*",end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [1]:
for i in range(1,6):
    print(' '*(5-i),'*'*(i*2-1))
    

     *
    ***
   *****
  *******
 *********


In [2]:
for i in range(1,6):
    print(' '*(i),'*'*(11-i*2))

  *********
   *******
    *****
     ***
      *


In [11]:
for i in range(1,6):
    print(' '*(5-i),'*'*(i*2-1))
for j in range(1,6):
    print(' '*(j-1),'*'*(11-j*2))

     *
    ***
   *****
  *******
 *********
 *********
  *******
   *****
    ***
     *


In [ ]:
y1,-1):
        print(" ",end=" ")
    for b in range(1,i*2):/.
        print("*",end=" ")
    print()

          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 1.0 MB/s eta 0:00:12
   - -------------------------------------- 0.5/12.7 MB 1.0 MB/s eta 0:00:12
   -- ------------------------------------- 0.8/12.7 MB 902.9 kB/s eta 0:00:14
   --- ------------------------------------ 1.0/12.7 MB 897.9 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.7 MB 897.9 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.7 MB 817.7 kB/s eta 0:00:14
   ---- ----------------------------------- 1.6/12.7 MB 829.6 kB/s eta 0:00:14
   ----- ---------------------------------- 1.8/12.7 MB 877.1 kB/s eta 0:00:13
   ------ --------------------------------- 2.1/12.7 MB 913.9 kB/s eta 0:00:12
   --


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np
x=np.array([1,2,3])
y=np.array([[1,2],[3,4]])
print(x)
print(y)

[1 2 3]
[[1 2]
 [3 4]]


In [14]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
